<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Repositories/IRepository.fs" />
    <Compile Include="Repositories/Repository.fs" />
    <Compile Include="Repositories/TestRepository.fs" />
    <Compile Include="Data/ApplicationDbContext.fs" />
    <Compile Include="UnitOfWork/IUnitOfWork.fs" />
    <Compile Include="UnitOfWork/UnitOfWork.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../TestApp.Domain/TestApp.Domain.fsproj" />
    <ProjectReference Include="../TestApp.Core/TestApp.Core.fsproj" />
  </ItemGroup>

</Project>
