<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TestApp.Core\TestApp.Core.csproj" />
    <ProjectReference Include="..\TestApp.Domain\TestApp.Domain.csproj" />
    <ProjectReference Include="..\TestApp.Messaging\TestApp.Messaging.csproj" />
  </ItemGroup>
</Project>
