// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestApp.Infrastructure.Persistence;

#nullable disable

namespace TestApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestApp.Domain.Assignments.TestAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("AttemptLimit")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AvailableFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("AvailableUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CancelledBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RevisionId");

                    b.HasIndex("TargetType", "TargetId", "Status");

                    b.ToTable("test_assignments", (string)null);
                });

            modelBuilder.Entity("TestApp.Domain.Attempts.TestAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeadlineAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Outcome")
                        .HasColumnType("integer");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StartRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId", "UserId");

                    b.HasIndex("AssignmentId", "UserId", "StartRequestId")
                        .IsUnique();

                    b.HasIndex("RevisionId", "Status", "Outcome");

                    b.ToTable("test_attempts", (string)null);
                });

            modelBuilder.Entity("TestApp.Domain.Revisions.PublishedTestRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<decimal>("PassingPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TimeLimitMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<string>("_questions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("questions_json");

                    b.HasKey("Id");

                    b.HasIndex("TestId", "Version")
                        .IsUnique();

                    b.ToTable("published_test_revisions", (string)null);
                });

            modelBuilder.Entity("TestApp.Domain.Tests.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Status");

                    b.ToTable("tests", (string)null);
                });

            modelBuilder.Entity("TestApp.Infrastructure.Outbox.OutboxDeadLetterAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("EventId", "OccurredAt");

                    b.ToTable("outbox_dead_letter_actions", (string)null);
                });

            modelBuilder.Entity("TestApp.Infrastructure.Persistence.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("DurationMs")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("ActorId", "OccurredAt");

                    b.HasIndex("StatusCode", "OccurredAt");

                    b.ToTable("audit_entries", (string)null);
                });

            modelBuilder.Entity("TestApp.Infrastructure.Persistence.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RequestFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResultType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Operation", "ActorId", "RequestId")
                        .IsUnique();

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("TestApp.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DiscardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt", "DeadLetteredAt", "DiscardedAt", "NextAttemptAt", "OccurredAt");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("TestApp.Domain.Attempts.TestAttempt", b =>
                {
                    b.OwnsOne("TestApp.Domain.Attempts.AttemptScore", "Score", b1 =>
                        {
                            b1.Property<Guid>("TestAttemptId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Earned")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("score_earned");

                            b1.Property<decimal>("Maximum")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("score_maximum");

                            b1.HasKey("TestAttemptId");

                            b1.ToTable("test_attempts");

                            b1.WithOwner()
                                .HasForeignKey("TestAttemptId");
                        });

                    b.OwnsMany("TestApp.Domain.Attempts.QuestionResponse", "Responses", b1 =>
                        {
                            b1.Property<Guid>("TestAttemptId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("AnsweredAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("TestAttemptId", "Id");

                            b1.ToTable("question_responses", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TestAttemptId");

                            b1.OwnsMany("TestApp.Domain.Attempts.SelectedAnswerOption", "SelectedOptions", b2 =>
                                {
                                    b2.Property<Guid>("TestAttemptId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("QuestionId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("OptionId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("TestAttemptId", "QuestionId", "OptionId");

                                    b2.ToTable("selected_answer_options", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("TestAttemptId", "QuestionId");
                                });

                            b1.Navigation("SelectedOptions");
                        });

                    b.Navigation("Responses");

                    b.Navigation("Score");
                });

            modelBuilder.Entity("TestApp.Domain.Tests.Test", b =>
                {
                    b.OwnsMany("TestApp.Domain.Tests.Question", "Questions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<int>("Order")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Points")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.Property<Guid>("TestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("TestId");

                            b1.ToTable("questions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TestId");

                            b1.OwnsMany("TestApp.Domain.Tests.AnswerOption", "Options", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("IsCorrect")
                                        .HasColumnType("boolean");

                                    b2.Property<int>("Order")
                                        .HasColumnType("integer");

                                    b2.Property<Guid>("QuestionId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Text")
                                        .IsRequired()
                                        .HasMaxLength(2000)
                                        .HasColumnType("character varying(2000)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("QuestionId");

                                    b2.ToTable("answer_options", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("QuestionId");
                                });

                            b1.Navigation("Options");
                        });

                    b.OwnsOne("TestApp.Domain.Tests.TestSettings", "Settings", b1 =>
                        {
                            b1.Property<Guid>("TestId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("PassingPercentage")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("passing_percentage");

                            b1.Property<int?>("TimeLimitMinutes")
                                .HasColumnType("integer")
                                .HasColumnName("time_limit_minutes");

                            b1.HasKey("TestId");

                            b1.ToTable("tests");

                            b1.WithOwner()
                                .HasForeignKey("TestId");
                        });

                    b.Navigation("Questions");

                    b.Navigation("Settings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
